from python:3.9-slim

WORKDIR /app

COPY src/producer.py /app
COPY config/config.yaml /app/config/
COPY requirements.txt /app
COPY logs/producer.log /app/logs/producer.log

RUN pip install -r requirements.txt

CMD ["python", "producer.py"]
