from python:3.9-slim

WORKDIR /app

COPY src/consumer.py /app
COPY config/config.yaml /app/config/
COPY requirements.txt /app
COPY logs/consumer.log /app/logs/consumer.log

RUN pip install -r requirements.txt

CMD ["python", "consumer.py"]
